source("load.R")
data<-loaddata()
par(mfcol=c(2,2))
plot(data$Time, data$Global_active_power, type="n", ylab="Global Active Power", xlab="")
lines(data$Time, data$Global_active_power)
plot(data$Time, data$Sub_metering_1, type="n", ylab="Energy sub metering", xlab="")
lines(data$Time, data$Sub_metering_1, col="black")
lines(data$Time, data$Sub_metering_2, col="red")
lines(data$Time, data$Sub_metering_3, col="blue")
legend("topright",lty = "solid", y.intersp=0.3,col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), cex=0.7, bty="n")
plot(data$Time, data$Voltage, type="n", ylab="Voltage", xlab="datetime")
lines(data$Time, data$Voltage)
plot(data$Time, data$Global_reactive_power, type="n", ylab="Global_reactive_power", xlab="datetime")
lines(data$Time, data$Global_reactive_power)
dev.copy(png,"plot4.png")
dev.off()